apiVersion: v1
kind: Service
metadata:
    name: smart-food-fe-service
    labels:
        app: smart-food-fe
spec:
    type: ClusterIP
    selector:
        app: smart-food-fe
    ports:
        - port: 80
          targetPort: 3000
