apiVersion: v1
kind: Service
metadata:
    name: smart-food-fe-service
    labels:
        app: smart-food-fe
spec:
    type: ClusterIP
    selector:
        app: smart-food-fe
    ports:
        - name: smart-food-fe
          protocol: TCP
          port: 3000
          targetPort: 3000
