apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: smart-food-ingress
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/use-regex: 'true'
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/enable-cors: 'true'
        nginx.ingress.kubernetes.io/cors-allow-methods: '*'
        nginx.ingress.kubernetes.io/cors-allow-origin: '*'
        nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
spec:
    rules:
        - http:
              paths:
                  - path: /apt/?(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: smart-food-be-service
                            port:
                                number: 8000

                  - path: /?(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: smart-food-fe-service
                            port:
                                number: 3000
